version: "3.8"
services:
  baseapp:
    image: registry.local:5000/adadevopsmod3:baseapp
    build:
      context: ./
      dockerfile: dockerfiles/baseapp.dockerfile
    container_name: baseapp
  criaambapp:
    image: registry.local:5000/adadevopsmod3:criaambapp
    build:
      context: ./
      dockerfile: dockerfiles/criaambapp.dockerfile
    container_name: criaambapp
  producerapp:
    image: registry.local:5000/adadevopsmod3:producerapp
    build:
      context: ./
      dockerfile: dockerfiles/producerapp.dockerfile
    container_name: producerapp
  consumerapp:
    image: registry.local:5000/adadevopsmod3:consumerapp
    build:
      context: ./
      dockerfile: dockerfiles/consumerapp.dockerfile
    container_name: consumerapp
