apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumerapp-deployment
  namespace: nsadadevopsmod3
  labels:
    app: consumerapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumerapp
  template:
    metadata:
      labels:
        app: consumerapp
    spec:
      initContainers:
      - name: wait-for-criaamb
        image: bitnami/kubectl
        command: ["sh", "-c", "until kubectl get job criaambapp-job -o=jsonpath='{.status.succeeded}' | grep -q 1; do echo Waiting for criaamb job to complete; sleep 5; done"]
      containers:
      - name: consumerapp
        image: localhost:5000/adadevopsmod3:baseapp
        command: ["python3", "/appfiles/consumer.py"]
        envFrom:
        - secretRef:
            name: minio-credentials
        - secretRef:
            name: rabbitmq-credentials
        volumeMounts:
        - name: python-files-volume
          mountPath: /appfiles
        resources:
          limits:
            memory: 256Mi
            cpu: "0.4"
          requests:
            memory: 128Mi
            cpu: "0.2"
      volumes:
      - name: python-files-volume
        persistentVolumeClaim:
          claimName: python-files-pvc