apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  namespace: nsadadevopsmod3
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:RELEASE.2024-03-07T00-43-48Z
        args:
        - server
        - /data
        - --console-address
        - ":9001"
        ports:
        - containerPort: 9000
        - containerPort: 9001
        volumeMounts:
        - name: minio-data
          mountPath: /data
        env:
        - name: MINIO_BROWSER_REDIRECT_URL
          value: "http://projadadevops.local"
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: MINIO_ROOT_USR
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: MINIO_ROOT_PWD
        startupProbe:
          exec:
            command:
            - /bin/sh
            - -c 
            - mc alias set myminio http://localhost:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD";
            - mc admin info myminio --insecure;
          initialDelaySeconds: 10
          timeoutSeconds: 5
        resources:
          limits:
            memory: 256Mi
            cpu: "0.4"
          requests:
            memory: 128Mi
            cpu: "0.2"
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio-pvc
