# Criando ConfigMap para o RabbitMQ
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-configmap
  namespace: nsadadevopsmod3
data:
  rabbitmq.conf: |
    listeners.tcp.default = 5672
    management.listener.port = 15672
    default_vhost = projetoada
    heartbeat = 30
    log.file = true
    log.exchange = true