apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-status-checker-binding
  namespace: nsadadevopsmod3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-status-checker
subjects:
- kind: ServiceAccount
  name: default
  namespace: nsadadevopsmod3