apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: nsadadevopsmod3
  name: job-status-checker
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]
