# Criando Secrets para o Minio
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: nsadadevopsmod3
type: Opaque
data:
  #admin
  MINIO_ROOT_USR: YWRtaW4=
  #admin1234
  MINIO_ROOT_PWD: YWRtaW4xMjM0
---
# Criando Secrets para o RabbitMQ
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: nsadadevopsmod3
type: Opaque
data:
  #admin
  RABBITMQ_ROOT_USR: YWRtaW4=
  #admin1234
  RABBITMQ_ROOT_PWD: YWRtaW4xMjM0