apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: nsadadevopsmod3
spec:
  ports:
  - name: http
    port: 9000
    targetPort: 9000
  - name: console  
    port: 9001
    targetPort: 9001
  type: ClusterIP
  selector:
    app: minio