apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: nsadadevopsmod3
spec:
  ports:
  - name: api
    port: 5672
    targetPort: 5672
  - name: http
    port: 15672
    targetPort: 15672
  selector:
    app: rabbitmq
