apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: nsadadevopsmod3
spec:
  ports:
  - name: console
    port: 6379
    targetPort: 6379
  - name: http
    port: 8001
    targetPort: 8001
  type: ClusterIP
  selector:
    app: redis