apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  namespace: nsadadevopsmod3
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: projadadevops.local
    http:
      paths:
      - path: "/minio(/|$)(.*)"
        pathType: ImplementationSpecific
        backend:
          service:
            name: minio-service
            port:
              number: 9001
      - path: "/minioapi(/|$)(.*)"
        pathType: ImplementationSpecific
        backend:
          service:
            name: minio-service
            port:
              number: 9000