apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-ingress
  namespace: nsadadevopsmod3
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: projadadevops.local
    http:
      paths:
      - path: "/redis(/|$)(.*)"
        pathType: ImplementationSpecific
        backend:
          service:
            name: redis-service
            port:
              number: 8001