apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: python-files-pvc
  namespace: nsadadevopsmod3
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi